import "./globals.css";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import CustomNavbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomNavbar />
        {children}
      </body>
    </html>
  );
}
